site_name: Alimazon
theme:
    name: rtd-dropdown
pages:
    - Overview: index.md
    - Data specification:
        - Orders specification: specs/orders.md
        - Articles specification: specs/articles.md
        - Clients specification: specs/clients.md
    - Appendixes:
        - Categories: appendixes/categories.md
        - Country codes: appendixes/country_codes.md
