site_name: Alimazon
theme:
    name: rtd-dropdown
pages:
    - Overview: index.md
    - Data Specification:
        - Clients: specs/clients.md
        - Stock Purchase Orders: specs/stock_purchase_orders.md
        - Client Purchase Orders: specs/client_purchase_orders.md
    - Appendixes:
        - Categories: appendixes/categories.md
        - Country codes: appendixes/country_codes.md
markdown_extensions:
    - del_ins
