site_name: Alimazon
theme:
    name: rtd-dropdown
pages:
    - Overview: index.md
    - Data Specification:
        - Clients: specs/clients.md
        - Buy Orders: specs/buy_orders.md
        - Sell Orders: specs/sell_orders.md
    - Appendixes:
        - Categories: appendixes/categories.md
        - Country codes: appendixes/country_codes.md
markdown_extensions:
    - del_ins
